spring:
  application:
    name: education-platform

  datasource:
    url: jdbc:postgresql://localhost:5432/education_platform
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
  secret: "4a607205a10960f4ae56101c89508643b3e640f4e0337e607c38c2c427a61973"
  expiration: 86400000

logging:
  level:
    root: INFO
    edu.platform: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

info:
  app:
    name: Education Platform
    description: REST API образовательной платформы
    version: 0.0.1-SNAPSHOT
    java-version: 21
    spring-boot-version: 4.1.1
  author:
    name: Максим
    group: ИВТ44у

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always